create table states_location
(
    state       varchar(100),
    description varchar,
    url         varchar
);

INSERT INTO states_location(state, description, url) VALUES ('ohio', 'Ohio is positioned in both the northern and western  .   As a part of North America, Ohio is located in the East North Central region of the United States. It''s bordered by the states of Pennsylvania, West Virginia, Kentucky, Indiana and Michigan, and by Lake Erie.
', 'https://www.worldatlas.com/webimage/countrys/namerica/usstates/ohlatlog.htm') ON CONFLICT DO NOTHING;
INSERT INTO states_location(state, description, url) VALUES ('virginia', 'Virginia is positioned in both the northern and western  .   As a part of North America, Virginia is located in the South Atlantic region of the United States. It''s bordered by the states of North Carolina, Tennessee, Kentucky, West Virginia and Maryland, and by Washington, D.C.; the Chesapeake Bay and Atlantic Ocean.
', 'https://www.worldatlas.com/webimage/countrys/namerica/usstates/valatlog.htm') ON CONFLICT DO NOTHING;
INSERT INTO states_location(state, description, url) VALUES ('wisconsin', 'Wisconsin is positioned in both the northern and western  .   As a part of North America, Wisconsin is located in the East North Central region of the United States. It''s bordered by the states of Illinois, Iowa, Minnesota, and Michigan, and by Lake Michigan and Lake Superior.
', 'https://www.worldatlas.com/webimage/countrys/namerica/usstates/wilatlog.htm') ON CONFLICT DO NOTHING;
INSERT INTO states_location(state, description, url) VALUES ('delaware', 'As a part of North America, Delaware is located in the South Atlantic region of the United States. It''s bordered by the states of Maryland, Pennsylvania and New Jersey and the Atlantic Ocean, Delaware Bay and Delaware River.
', 'https://www.worldatlas.com/webimage/countrys/namerica/usstates/delatlog.htm') ON CONFLICT DO NOTHING;
INSERT INTO states_location(state, description, url) VALUES ('kentucky', 'Kentucky is positioned in both the northern and western  .   As a part of North America, Kentucky is located in the East South Central region of the United States. It''s bordered by seven states, including Virginia, Tennessee, Missouri, Illinois, Indiana, Ohio and West Virginia.
', 'https://www.worldatlas.com/webimage/countrys/namerica/usstates/kylatlog.htm') ON CONFLICT DO NOTHING;
INSERT INTO states_location(state, description, url) VALUES ('georgia', 'Georgia is positioned in both the northern and western  .  Located in the southeastern region of the United States, a part of North America, Georgia is bordered by the states of Alabama, Tennessee, North Carolina, South Carolina and Florida, and by the Atlantic Ocean.
', 'https://www.worldatlas.com/webimage/countrys/namerica/usstates/galatlog.htm') ON CONFLICT DO NOTHING;
INSERT INTO states_location(state, description, url) VALUES ('mississippi', 'Mississippi is positioned in both the northern and western  .   Located in the Gulf Coast region of the United States of America - a part of North America - Mississippi is bordered by the states of Louisiana, Arkansas, Tennessee and Alabama; the Mississippi River along its entire western border, and by the Gulf of Mexico.
', 'https://www.worldatlas.com/webimage/countrys/namerica/usstates/mslatlog.htm') ON CONFLICT DO NOTHING;
INSERT INTO states_location(state, description, url) VALUES ('oregon', 'Oregon is positioned in both the northern and western  . Located in the Pacific Northwest region of the United States of America - a part of North America - Oregon is bordered by the states of  Washington,  Idaho,  Nevada, and  California, and by the  Pacific Ocean.
', 'https://www.worldatlas.com/webimage/countrys/namerica/usstates/orlatlog.htm') ON CONFLICT DO NOTHING;
INSERT INTO states_location(state, description, url) VALUES ('pennsylvania', 'Pennsylvania is positioned in both the northern and western  .   As a part of North America, Pennsylvania is located in the Middle Atlantic region of the United States. It''s bordered by the states of New York, New Jersey, Delaware, Maryland, West Virginia and Ohio, and by Lake Erie and the Delaware River.
', 'https://www.worldatlas.com/webimage/countrys/namerica/usstates/palatlog.htm') ON CONFLICT DO NOTHING;
INSERT INTO states_location(state, description, url) VALUES ('north dakota', 'North Dakota is positioned in both the northern and western  . Located in the North Central (or Midwest Region) of the United States of America - a part of North America - North Dakota is bordered by the states of Montana, Minnesota, South Dakota, and by the Canadian provinces of Saskatchewan and Manitoba.
', 'https://www.worldatlas.com/webimage/countrys/namerica/usstates/ndlatlog.htm') ON CONFLICT DO NOTHING;
INSERT INTO states_location(state, description, url) VALUES ('michigan', 'As a part of North America, Michigan is located in the East North Central region of the United States. It''s bordered by the states of Ohio, Indiana and Wisconsin; the Canadian province of Ontario, and by Lake Michigan, Lake Superior, Lake Huron and Lake Erie.
', 'https://www.worldatlas.com/webimage/countrys/namerica/usstates/milatlog.htm') ON CONFLICT DO NOTHING;
INSERT INTO states_location(state, description, url) VALUES ('nevada', 'Nevada is positioned in both the northern and western  . Located in the western region of the United States of America - a part of North America - Nevada is bordered by the states of California, Oregon, Idaho, Utah and Arizona
', 'https://www.worldatlas.com/webimage/countrys/namerica/usstates/nvlatlog.htm') ON CONFLICT DO NOTHING;
INSERT INTO states_location(state, description, url) VALUES ('arizona', 'Arizona is positioned in both the northern and western  . Located in the southwestern region of the United States of America - a part of North America - Arizona is bordered by the states of California, Nevada, Utah, Colorado, New Mexico, and by the country of Mexico.
', 'https://www.worldatlas.com/webimage/countrys/namerica/usstates/azlatlog.htm') ON CONFLICT DO NOTHING;
INSERT INTO states_location(state, description, url) VALUES ('alabama', 'Alabama is positioned in both the northern and western  .   Located in the southeastern region of the United States, a part of North America, Alabama is bordered by the states of Florida,  Georgia,  Mississippi, Tennessee, and the Gulf of Mexico.
', 'https://www.worldatlas.com/webimage/countrys/namerica/usstates/allatlog.htm') ON CONFLICT DO NOTHING;
INSERT INTO states_location(state, description, url) VALUES ('new hampshire', ')

New Hampshire is positioned in both the northern and western  .

As a part of North America and located in the northeastern region of the United States (one often referred to as New England), New Hampshire is bordered by the states of Maine, Massachusetts, Vermont, the Atlantic Ocean, and the Canadian province of Quebec.



', 'https://www.worldatlas.com/webimage/countrys/namerica/usstates/nhlatlog.htm') ON CONFLICT DO NOTHING;
INSERT INTO states_location(state, description, url) VALUES ('tennessee', 'Tennessee is positioned in both the northern and western  .   As a part of North America, Tennessee is located in the East South Central region of the United States. It''s bordered by eight states, including Arkansas, Missouri, Kentucky, Virginia, North Carolina, Georgia, Alabama and Mississippi.
', 'https://www.worldatlas.com/webimage/countrys/namerica/usstates/tnlatlog.htm') ON CONFLICT DO NOTHING;
INSERT INTO states_location(state, description, url) VALUES ('florida', 'The State of Florida is positioned in both the northern and western  .   Located in the far southeastern region of the United States, a part of North America, Florida is bordered by the states of Alabama and Georgia also by the Atlantic Ocean, Gulf of Mexico and the Straits of Florida.
', 'https://www.worldatlas.com/webimage/countrys/namerica/usstates/fllatlog.htm') ON CONFLICT DO NOTHING;
INSERT INTO states_location(state, description, url) VALUES ('iowa', 'Iowa is positioned in both the northern and western  . Located in the North Central (or Midwest Region) of the United States of America - a part of North America - Iowa is bordered by the states of  Minnesota ,  Wisconsin,  Illinois,  Missouri, Nebraska and   South Dakota.
', 'https://www.worldatlas.com/webimage/countrys/namerica/usstates/ialatlog.htm') ON CONFLICT DO NOTHING;
INSERT INTO states_location(state, description, url) VALUES ('massachusetts', 'Massachusetts is positioned in both the northern and western  .   As a part of North America and located in the northeastern region of the United States (one often referred to as New England), Massachusetts is bordered by the Atlantic Ocean, Rhode Island, Connecticut, New York, Vermont and New Hampshire.
', 'https://www.worldatlas.com/webimage/countrys/namerica/usstates/malatlog.htm') ON CONFLICT DO NOTHING;
INSERT INTO states_location(state, description, url) VALUES ('connecticut', 'Connecticut is positioned in both the northern and western  .   As a part of North America and located in the northeastern region of the United States (one often referred to as New England), Connecticut is bordered by the states of Rhode Island, Massachusetts and New York, and Long Island Sound and the Atlantic Ocean.
', 'https://www.worldatlas.com/webimage/countrys/namerica/usstates/ctlatlog.htm') ON CONFLICT DO NOTHING;
INSERT INTO states_location(state, description, url) VALUES ('new york', 'New York is positioned in both the northern and western  .
', 'https://www.worldatlas.com/webimage/countrys/namerica/usstates/nylatlog.htm') ON CONFLICT DO NOTHING;
INSERT INTO states_location(state, description, url) VALUES ('west virginia', 'West Virginia is positioned in both the northern and western  .   As a part of North America, West Virginia is located in the South Atlantic region of the United States. It''s bordered by the states of Virginia, Kentucky, Ohio, Pennsylvania and Maryland
', 'https://www.worldatlas.com/webimage/countrys/namerica/usstates/wvlatlog.htm') ON CONFLICT DO NOTHING;
INSERT INTO states_location(state, description, url) VALUES ('maryland', 'Maryland is positioned in both the northern and western  .   As a part of North America, Maryland is located in the South Atlantic region of the United States. It''s bordered by the states of Virginia, West Virginia, Pennsylvania and Delaware and by Washington, D.C., and the Chesapeake Bay.
', 'https://www.worldatlas.com/webimage/countrys/namerica/usstates/mdlatlog.htm') ON CONFLICT DO NOTHING;
INSERT INTO states_location(state, description, url) VALUES ('wyoming', 'Wyoming is positioned in both the northern and western  . Located in the west-central region (or Mountain States area) of the United States of America, a part of North America - Wyoming is bordered by the states of Utah, Idaho, Montana, South Dakota, Nebraska and Colorado.
', 'https://www.worldatlas.com/webimage/countrys/namerica/usstates/wylatlog.htm') ON CONFLICT DO NOTHING;
INSERT INTO states_location(state, description, url) VALUES ('idaho', 'Idaho is positioned in both the northern and western  . Located in the west central region (or Mountain States area) of the United States of America - a part of North America - Idaho is bordered by the states of  Montana,  Wyoming,  Utah,  Nevada,  Oregon Washington and by the Canadian Province of British Columbia.
', 'https://www.worldatlas.com/webimage/countrys/namerica/usstates/idlatlog.htm') ON CONFLICT DO NOTHING;
INSERT INTO states_location(state, description, url) VALUES ('arkansas', 'Arkansas is positioned in both the northern and western  . Located in the south-central region of the United States of America - a part of North America - Arkansas is bordered by the states of Louisiana, Texas, Oklahoma, Missouri, Tennessee and Mississippi .
', 'https://www.worldatlas.com/webimage/countrys/namerica/usstates/arlatlog.htm') ON CONFLICT DO NOTHING;
INSERT INTO states_location(state, description, url) VALUES ('hawaii', 'The State of Hawaii is located in the North Pacific Ocean just a few degrees south of the  Tropic of Cancer, approximately  2,550 miles southwest of Los Angeles and about 3,900 miles southeast of Tokyo.   Because of its isolated location, Hawaii is not considered a part of the North American Continent
', 'https://www.worldatlas.com/webimage/countrys/namerica/usstates/hilatlog.htm') ON CONFLICT DO NOTHING;
INSERT INTO states_location(state, description, url) VALUES ('maine', 'Maine is positioned in both the northern and western  . As a part of North America and located in the northeastern region of the United States (one often referred to as New England), Maine is bordered by the Atlantic Ocean, State of New Hampshire, and the Canadian provinces of New Brunswick and Quebec.
', 'https://www.worldatlas.com/webimage/countrys/namerica/usstates/melatlog.htm') ON CONFLICT DO NOTHING;
INSERT INTO states_location(state, description, url) VALUES ('indiana', 'Indiana is positioned in both the northern and western  .   As a part of North America, Indiana is located in the East North Central region of the United States. It''s bordered by the states of Michigan, Ohio, Kentucky, Illinois, and by Lake Michigan.
', 'https://www.worldatlas.com/webimage/countrys/namerica/usstates/inlatlog.htm') ON CONFLICT DO NOTHING;
INSERT INTO states_location(state, description, url) VALUES ('missouri', 'Missouri is positioned in both the northern and western  . Located in the central (or Midwest Region) of the United States of America, a part of North America - Missouri is bordered by the states of Kansas, Nebraska, Iowa, Illinois, Kentucky, Tennessee, Arkansas and Oklahoma
', 'https://www.worldatlas.com/webimage/countrys/namerica/usstates/molatlog.htm') ON CONFLICT DO NOTHING;
INSERT INTO states_location(state, description, url) VALUES ('montana', 'Montana is positioned in both the northern and western  . Located in the west central region (or Mountain States area) of the United States of America - a part of North America - Montana is bordered by the states of  Idaho,  North Dakota,  South Dakota Wyoming and by the country of  Canada.
', 'https://www.worldatlas.com/webimage/countrys/namerica/usstates/mtlatlog.htm') ON CONFLICT DO NOTHING;
INSERT INTO states_location(state, description, url) VALUES ('texas', 'Texas is positioned in both the northern and western  .   Located in the southern Gulf-Coast region of the United States of America - a part of North America - it''s bordered by the U.S. States of New Mexico, Oklahoma, Arkansas, Louisiana, as well as the Gulf of Mexico.   In addition, it''s bordered by the Rio Grande River that forms the state''s entire border with the country of Mexico, a border 1,951 miles - 3,141 km in length.
', 'https://www.worldatlas.com/webimage/countrys/namerica/usstates/txlatlog.htm') ON CONFLICT DO NOTHING;
INSERT INTO states_location(state, description, url) VALUES ('alaska', 'Alaska is positioned in both the eastern, northern and western  .   Dissected by the  Arctic Circle, it''s located in the far northwestern corner of  North America, bordering the Canadian province of  British Columbia and Canada''s Yukon Territory.   It''s ringed by the Arctic Ocean, Pacific Ocean, and assorted bays, gulfs, seas and sounds.
', 'https://www.worldatlas.com/webimage/countrys/namerica/usstates/aklatlog.htm') ON CONFLICT DO NOTHING;
INSERT INTO states_location(state, description, url) VALUES ('south dakota', 'South Dakota is positioned in both the northern and western  . Located in the North Central (or Midwest Region) of the United States of America - a part of North America - South Dakota is bordered by the states of Wyoming, Montana, North Dakota, Minnesota, Iowa. Nebraska.
', 'https://www.worldatlas.com/webimage/countrys/namerica/usstates/sdlatlog.htm') ON CONFLICT DO NOTHING;
INSERT INTO states_location(state, description, url) VALUES ('kansas', 'Kansas is positioned in both the northern and western  . Located in the central region of the United States of America, a part of North America - Kansas is bordered by the states of Nebraska, Missouri, Oklahoma and Colorado.
', 'https://www.worldatlas.com/webimage/countrys/namerica/usstates/kslatlog.htm') ON CONFLICT DO NOTHING;
INSERT INTO states_location(state, description, url) VALUES ('utah', 'Utah is positioned in both the northern and western  . Located in the west-central region (or Mountain States area) of the United States of America, a part of North America - Utah is bordered by the states of Nevada, Idaho, Wyoming, Colorado, New Mexico and Arizona.
', 'https://www.worldatlas.com/webimage/countrys/namerica/usstates/utlatlog.htm') ON CONFLICT DO NOTHING;
INSERT INTO states_location(state, description, url) VALUES ('illinois', 'Illinois is positioned in both the northern and western  .   As a part of North America, Illinois is located in the East North Central region of the United States. It''s bordered by the states of Indiana, Kentucky, Missouri, Iowa and Wisconsin, and by Lake Michigan.
', 'https://www.worldatlas.com/webimage/countrys/namerica/usstates/illatlog.htm') ON CONFLICT DO NOTHING;
INSERT INTO states_location(state, description, url) VALUES ('louisiana', 'Louisiana is positioned in both the northern and western  . Located in the Gulf Coast region of the United States of America - a part of North America - Louisiana is bordered by the states of Arkansas, Mississippi and Texas and the Gulf of Mexico.
', 'https://www.worldatlas.com/webimage/countrys/namerica/usstates/lalatlog.htm') ON CONFLICT DO NOTHING;
INSERT INTO states_location(state, description, url) VALUES ('new jersey', 'As a part of North America, New Jersey is located in the Middle Atlantic region of the United States. It''s bordered by the states of New York, Pennsylvania, Delaware, and by the Atlantic Ocean, Delaware Bay, Delaware River, New York Bay and Hudson River.
', 'https://www.worldatlas.com/webimage/countrys/namerica/usstates/njlatlog.htm') ON CONFLICT DO NOTHING;
INSERT INTO states_location(state, description, url) VALUES ('oklahoma', 'Oklahoma is positioned in both the northern and western  . Located in the south-central region of the United States of America, a part of North America - Oklahoma is bordered by the states of New Mexico, Colorado, Kansas, Missouri, Arkansas and Texas.
', 'https://www.worldatlas.com/webimage/countrys/namerica/usstates/oklatlog.htm') ON CONFLICT DO NOTHING;
INSERT INTO states_location(state, description, url) VALUES ('rhode island', 'Rhode Island is positioned in both the northern and western  .   As a part of North America and located in the northeastern region of the United States (one often referred to as New England), Rhode Island is bordered by the states of Connecticut and Massachusetts, and by Block Island Sound and Rhode Island Sound, both extensions of the Atlantic Ocean.
', 'https://www.worldatlas.com/webimage/countrys/namerica/usstates/rilatlog.htm') ON CONFLICT DO NOTHING;
INSERT INTO states_location(state, description, url) VALUES ('minnesota', 'Minnesota is positioned in both the northern and western  . Located in the North Central (or Midwest Region) of the United States of America - a part of North America -  Minnesota is bordered by the states of  North Dakota,  South Dakota,  Iowa and  Wisconsin, the Canadian provinces of  Manitoba and  Ontario, and by  Lake Superior.
', 'https://www.worldatlas.com/webimage/countrys/namerica/usstates/mnlatlog.htm') ON CONFLICT DO NOTHING;
INSERT INTO states_location(state, description, url) VALUES ('north carolina', 'Geographically positioned in both the northern and western   and located in the eastern region of the United States, a part of North America, North Carolina is bordered by the states of South Carolina, Georgia, Tennessee and Virginia, and by the Atlantic Ocean.
', 'https://www.worldatlas.com/webimage/countrys/namerica/usstates/nclatlog.htm') ON CONFLICT DO NOTHING;
INSERT INTO states_location(state, description, url) VALUES ('south carolina', 'Geographically positioned in both the northern and western   and located in the southeastern region of the United States, a part of North America, South Carolina is bordered by the states of Georgia, North Carolina, and the Atlantic Ocean.
', 'https://www.worldatlas.com/webimage/countrys/namerica/usstates/sclatlog.htm') ON CONFLICT DO NOTHING;
INSERT INTO states_location(state, description, url) VALUES ('washington', 'Washington is positioned in both the northern and western  . Located in the Pacific Northwest region of the United States of America - a part of North America - Washington is bordered by the states of Idaho and Oregon, the Pacific Ocean, and by the Canadian province of British Columbia.
', 'https://www.worldatlas.com/webimage/countrys/namerica/usstates/walatlog.htm') ON CONFLICT DO NOTHING;
INSERT INTO states_location(state, description, url) VALUES ('new mexico', 'New Mexico is positioned in both the northern and western  . Located in the southwestern region of the United States of America - a part of North America - New Mexico is bordered by the states of Arizona, Utah, Colorado, Oklahoma, Texas, and by the country of Mexico.
', 'https://www.worldatlas.com/webimage/countrys/namerica/usstates/nmlatlog.htm') ON CONFLICT DO NOTHING;
INSERT INTO states_location(state, description, url) VALUES ('colorado', 'Colorado is positioned in both the northern and western  . Located in the west-central region (or Mountain States area) of the United States of America, a part of North America - Colorado is bordered by the states of  Utah,  Wyoming,  Nebraska,  Kansas,  Oklahoma,  New Mexico and  Arizona
', 'https://www.worldatlas.com/webimage/countrys/namerica/usstates/colatlog.htm') ON CONFLICT DO NOTHING;
INSERT INTO states_location(state, description, url) VALUES ('nebraska', 'Nebraska is positioned in both the northern and western  . Located in the central (or Midwest Region) of the United States of America, a part of North America - Nebraska is bordered by the states of Colorado, Wyoming, South Dakota, Iowa,Missouri and Kansas.
', 'https://www.worldatlas.com/webimage/countrys/namerica/usstates/nelatlog.htm') ON CONFLICT DO NOTHING;
INSERT INTO states_location(state, description, url) VALUES ('vermont', 'Vermont is positioned in both the northern and western  .   As a part of North America and located in the northeastern region of the United States (one often referred to as New England), Vermont is bordered by the states of Massachusetts, New York and New Hampshire, and the Canadian province of Quebec.
', 'https://www.worldatlas.com/webimage/countrys/namerica/usstates/vtlatlog.htm') ON CONFLICT DO NOTHING;
INSERT INTO states_location(state, description, url) VALUES ('california', 'California is positioned in both the northern and western  . Located in the western region of the United States of America - a part of North America - California is bordered by the states of Oregon, Nevada and Arizona; the Country of Mexico, and by the Pacific Ocean.
', 'https://www.worldatlas.com/webimage/countrys/namerica/usstates/calatlog.htm') ON CONFLICT DO NOTHING;

